sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - valgrind
    - cppcheck
    - sanitize
    - gcov
install:
- "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make
  - make test
  - valgrind --leak-check=full ./sort ./array ./get_opc
  #- gprof ./hello > gprof.log

