/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "sort.h"
#include "array.h"
#include "get_opt.h"



/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_insertion(void);


/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestSort.c");
  RUN_TEST(test_selection_array_random, 28); // testname + line number
  RUN_TEST(test_insertion_array_random, 46); 
  RUN_TEST(test_quick_array_random, 59); 
  RUN_TEST(test_selection_array_ascending, 74); 
  RUN_TEST(test_insertion_array_ascending, 92);
  RUN_TEST(test_shell_array_ascending, 108);
  RUN_TEST(test_insertion_array_almost, 139);
  
  return (UnityEnd());
}

